### ISSUE TITLE
Suggestion: config to disable potion tooltips

### ISSUE THREAD

**Issue by Partonetrain** [gliscowo/idwtialsimmoedm#18]
The mod currently adds tooltips to potions too, which should be mentioned on the modpage(s).
"display_on_books_only" seems to effect potions as well as books.

**Comment by gliscowo** [comment]
Thanks for the heads-up about the project descriptions, I've updated them to mention this fact. As for the option you're suggesting - I'm a bit bewildered why you'd want it. Given that adding descriptions to things is literally the core feature of this mod it seems a bit... counterproductive to disabled them. What's your potential use-case?

Cheers

**Comment by Partonetrain** [comment]
Simply put, I have another mod that does the same: ZenithAttributes. I actually made the same issue on that [repo](https://github.com/TheWinABagel/ZenithAttributes/issues/8), but the developer hasn't been very responsive to that repo's issues. Either mod adding the option would solve my particular problem

**Comment by gliscowo** [comment]
Seeing as adding descriptions is, well, the purpose of this mod *and* that ZenithAttributes has added an option on their side, I'll be closing this

Cheers
