### ISSUE TITLE
Incompatible with Indium

### ISSUE THREAD

**Issue by Scarlaid** [gliscowo/idwtialsimmoedm#2]
Yes, I was the one asked about the same issue in the Discord but no response, so I try to test every single mod that affect rendering myself, found out that Indium was the cause of "Resource loading failed"

- Run with Indium
Log: [latest.log](https://github.com/gliscowo/idwtialsimmoedm/files/8840749/latest.log)
Video: https://streamable.com/fndxbf

- Run without Indium
Log: [lastest.log](https://github.com/gliscowo/idwtialsimmoedm/files/8840753/lastest.log)
Video: https://streamable.com/luefks

My resource pack is 100% came from VanillaTweaks, every others are from the mods, already listed in the log

**Comment by gliscowo** [comment]
Fixed in [0.1.1](https://modrinth.com/mod/idwtialsimmoedm/version/6KJI4TmM), thank you for reporting
Cheers
