### ISSUE TITLE
[1.20.1]Crash when mouse on certain item.

### ISSUE THREAD

**Issue by rtxyd** [gliscowo/idwtialsimmoedm#21]
[crash-2024-06-05_15.45.45-client.txt](https://github.com/user-attachments/files/15579122/crash-2024-06-05_15.45.45-client.txt)
Move mouse onto bandage of Majrusz's Progressive Difficulty. Will crash.

**Comment by gliscowo** [comment]
Fixed in [0.3.1](https://modrinth.com/mod/idwtialsimmoedm/version/0.3.1+1.20), thanks for reporting
Cheers
