### ISSUE TITLE
Use JEED descriptions for status effects

### ISSUE THREAD

**Issue by anoomolu** [gliscowo/idwtialsimmoedm#27]
Hiya. For better mod compat, I was wondering if the status effect side of this mod could use the effect.modname.effect.description lang often provided by mods to display effects using Just Enough Effect Descriptions. A 1.20.1 backport would be amazing if this were implemented.

Noticed this after this convention was used for Botania effects not too long ago, but didn't show up here. One other tiny thing - the resistance effect has a tiny typo - "resistance **do** damage" rather than "to". Cheers for the lovely mod ^^

**Comment by gliscowo** [comment]
Thanks for bringing this to my attention! 

I've now implemented support for JEED's format (and fixed the resistance typo), both available in [0.3.2 for 1.21](https://modrinth.com/mod/ad89WlWh/version/2TVUrqbG)

Cheers
