### ISSUE TITLE
The symbol is marked as "?" for any Unicode characters as "symbol"

### ISSUE THREAD

**Issue by Scarlaid** [gliscowo/idwtialsimmoedm#3]
The mod seem to be unhappy with Unicode characters (calling it symbol) so it just "?" at any symbols used after saving the config
![image](https://user-images.githubusercontent.com/90851437/172451935-2a023999-ca39-47c0-bf2d-cd8f4bf858c3.png)

Weird enough, it still show the symbol in-game, but after a new launch, the symbol will be marked "?"
![image](https://user-images.githubusercontent.com/90851437/172452932-bd9af6f1-114f-4625-9005-f8584be27bbb.png)

To say that there are no mods conflicting the **idw** mod, here's an example from another mod, able to use Unicode characters
![image](https://user-images.githubusercontent.com/90851437/172452986-b00e5d90-db5e-4221-b672-4003961f2138.png)
![image](https://user-images.githubusercontent.com/90851437/172453011-4d09f61f-45aa-4d85-9749-0a614b756790.png)

**Comment by gliscowo** [comment]
Fixed in [0.1.2+1.19](https://modrinth.com/mod/idwtialsimmoedm/version/5HPjCQMl)
