### ISSUE TITLE
Can I add custom modded ecnhant description for idwtialsimmoedm mod with just lang files?

### ISSUE THREAD

**Issue by ardissaps** [gliscowo/idwtialsimmoedm#4]
if yes, should the lang in the idwtialsimmoedm folder or mod folder

**Comment by Noaaan** [comment]
There is no strict requirement on where the lang for modded enchants should be.
I recommend simply adding them to your mods language file.

**Comment by ardissaps** [comment]
Ok, I will try, thank you very much!
